Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AlWarraq.Models;

namespace AlWarraq.Controllers
{
    public class BooksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Books
        public ActionResult Index(string title, string author, decimal? minPrice, decimal? maxPrice, int? categoryId)
        {

            ViewBag.Categories = db.Categories.ToList();
            ViewBag.isAuthenticated = User.Identity.IsAuthenticated;
            var books = db.Books.AsQueryable();

            if (!string.IsNullOrEmpty(title))
            {
                books = books.Where(b => b.Title.Contains(title));
            }

            if (!string.IsNullOrEmpty(author))
            {
                books = books.Where(b => b.Author.Contains(author));
            }

            if (minPrice.HasValue)
            {
                books = books.Where(b => b.Price >= minPrice.Value);
            }

            if (maxPrice.HasValue)
            {
                books = books.Where(b => b.Price <= maxPrice.Value);
            }

            if (categoryId.HasValue)
            {
                books = books.Where(b => b.BookCategories.Any(bc => bc.CategoryId == categoryId.Value));
            }

            return View(books.ToList());
        }

        // GET: Books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var book = db.Books.Include(b => b.BookCategories.Select(c => c.Category)).FirstOrDefault(b => b.BookId == id);
            if (book == null)
            {
                return HttpNotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Book book, HttpPostedFileBase ImageFile)
        {
            if (ModelState.IsValid)
            {
                if (ImageFile != null && ImageFile.ContentLength > 0)
                {
                    // Set the folder path to save the uploaded images
                    string folderPath = Server.MapPath("~/Images/Books/");
                    // Create the directory if it doesn't exist
                    if (!Directory.Exists(folderPath))
                    {
                        Directory.CreateDirectory(folderPath);
                    }

                    // Generate a unique filename
                    string fileName = Path.GetFileNameWithoutExtension(ImageFile.FileName);
                    string extension = Path.GetExtension(ImageFile.FileName);
                    fileName = fileName + "_" + DateTime.Now.ToString("yymmssfff") + extension;
                    string fullPath = Path.Combine(folderPath, fileName);

                    // Save the file
                    ImageFile.SaveAs(fullPath);

                    // Store the path in the ImageUrl property
                    book.ImageUrl = "/Images/Books/" + fileName;
                }

                db.Books.Add(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(book);
        }


        // GET: Books/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BookId,Title,Author,ISBN,Price,StockQuantity,ImageUrl")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(book);
        }

        // GET: Books/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = db.Books.Find(id);
            db.Books.Remove(book);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/CartController.cs
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web.Mvc;
using AlWarraq.Models;
using Microsoft.AspNet.Identity;

namespace AlWarraq.Controllers
{
    public class CartController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        [Authorize]
        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Home");

            var user = User.Identity;
            var userId = user.GetUserId();
            var userCart = db.Carts.Include(cart => cart.CartItems.Select(ci => ci.Book)).FirstOrDefault(cart => cart.UserId == userId);
            if (userCart != null) return View(userCart.CartItems.ToList());
            userCart = new Cart
            {
                UserId = user.GetUserId()
            };
            db.Carts.Add(userCart);
            db.SaveChanges();
            var cartItems = userCart.CartItems.ToList();
            return View(cartItems);
        }

        [Authorize]
        public ActionResult AddQuantity(int? id)
        {
            var cartItem = db.CartItems.Find(id);
            if (cartItem == null) return Index();
            cartItem.Quantity++;
            db.CartItems.AddOrUpdate(cartItem);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        [Authorize]
        public ActionResult MinusQuantity(int? id)
        {
            var cartItem = db.CartItems.Find(id);
            if (cartItem == null) return Index();
            if (cartItem.Quantity > 1)
            {
                cartItem.Quantity--;
            }
            db.CartItems.AddOrUpdate(cartItem);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult AddToCart(int bookId)
        {

            var book = db.Books.Find(bookId);
            if (book == null) return Json(new { success = false });

            var userId = User.Identity.GetUserId();

            var cart = db.Carts.Include(cart1 => cart1.CartItems).FirstOrDefault(c => c.UserId == userId);
            if (cart == null)
            {
                cart = new Cart
                {
                    UserId = userId
                };
                db.Carts.Add(cart);
                db.SaveChanges();
            }

            var cartItem = cart.CartItems.FirstOrDefault(c => c.BookId == bookId);

            if (cartItem != null)
            {
                cartItem.Quantity++;
            }
            else
            {
                cartItem = new CartItem { BookId = bookId, Quantity = 1 };
                cart.CartItems.Add(cartItem);
            }

            db.SaveChanges();
            // Optionally, you can return the updated cart details or just a success message
            return Json(new { success = true, itemCount = cart.CartItems.Count() });
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Books/Create.cshtml
@model AlWarraq.Models.Book

@{
    ViewBag.Title = "Create";
}
<div class="container">

    <h2>Create</h2>

    @using (Html.BeginForm("Create", "Books", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Book</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ISBN, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ISBN, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ISBN, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StockQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.StockQuantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StockQuantity, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="ImageFile" class="form-control" />
                    @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Books/Delete.cshtml
@model AlWarraq.Models.Book

@{
    ViewBag.Title = "Delete";
}
<div class="container">

    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Book</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Author)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Author)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ISBN)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ISBN)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.StockQuantity)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.StockQuantity)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ImageUrl)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ImageUrl)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>

</div>

Views/Books/Details.cshtml
@using AlWarraq.Models
@model AlWarraq.Models.Book

@{
    ViewBag.Title = "Details";
}
<div class="container">

    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <img src="@Url.Content(Model.ImageUrl)" alt="@Model.Title" class="img-fluid">
            </div>
            <div class="col-md-8">
                <h1>@Model.Title</h1>
                <p><strong>Author:</strong> @Model.Author</p>
                <p><strong>ISBN:</strong> @Model.ISBN</p>
                <p><strong>Price:</strong> $@Model.Price</p>
                <p><strong>In Stock:</strong> @Model.StockQuantity</p>
                <p><strong>Description:</strong></p>
                <p>@Model.Description</p>

                <h4>Categories</h4>
                <ul>
                    @foreach (var category in Model.BookCategories)
                    {
                        <li>@category.Category.Name</li>
                    }
                </ul>

                <a href="@Url.Action("AddToCart", "Cart", new { id = Model.BookId })" class="btn btn-primary">Add to Cart</a>
                <a href="@Url.Action("Index", "Books")" class="btn btn-secondary">Back to List</a>
            </div>
        </div>
    </div>


</div>

Views/Books/Edit.cshtml
@model AlWarraq.Models.Book

@{
    ViewBag.Title = "Edit";
}
<div class="container">

    <h2>Edit</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Book</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.BookId)

            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ISBN, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ISBN, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ISBN, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StockQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.StockQuantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StockQuantity, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>

Views/Books/Index.cshtml
@using AlWarraq.Models
@model IEnumerable<AlWarraq.Models.Book>

@{
    ViewBag.Title = "Index";
    var categories = ViewBag.Categories as List<Category>;
}
<div class="container">
    <form method="get" class="p-3">
        <div class="row g-3">
            <!-- Filter by Title -->
            <div class="col-md-4">
                <label for="title" class="form-label">Title</label>
                <input type="text" class="form-control" id="title" name="title" placeholder="Enter book title">
            </div>

            <!-- Filter by Author -->
            <div class="col-md-4">
                <label for="author" class="form-label">Author</label>
                <input type="text" class="form-control" id="author" name="author" placeholder="Enter author name">
            </div>


            <!-- Filter by Price Range -->
            <div class="col-md-4">
                <label for="priceRange" class="form-label">Price Range</label>
                <div class="input-group">
                    <span class="input-group-text">$</span>
                    <input style="margin:0" type="number" class="form-control input-group-text" id="minPrice" name="minPrice" placeholder="Min" aria-label="Min Price">
                    <span class="input-group-text">-</span>
                    <input style="margin:0" type="number" class="form-control" id="maxPrice" name="maxPrice" placeholder="Max" aria-label="Max Price">
                </div>
            </div>

            <!-- Filter by Categories -->
            <div class="col-md-4">
                <label for="category" class="form-label">Category</label>
                <select class="form-select" id="category" name="categoryId">
                    <option value="">All Categories</option>
                    @foreach (var category in categories)
                    {
                        <option value="@category.CategoryId">@category.Name</option>
                    }
                </select>
            </div>

            <!-- Filter Button -->
            <div class="col-md-4 d-flex align-items-end">
                <button type="submit" class="btn btn-primary w-100">Filter</button>
            </div>
        </div>
    </form>

    <div class="row">
        @foreach (var book in Model)
        {
            <div class="col-md-3">
                <div class="product-item">
                    <figure class="product-style">
                        <img src="@Url.Content(book.ImageUrl)" alt="Books" class="product-item">
                        <button type="button" class="add-to-cart" data-id="@book.BookId" data-product-tile="add-to-cart">
                            Add to
                            Cart
                        </button>
                    </figure>
                    <figcaption>
                        <h3>@book.Title</h3>
                        <span>@book.Author</span>
                        <div class="item-price">$ @book.Price</div>
                    </figcaption>
                </div>
            </div>
        }
    </div>

    @if (ViewBag.isAuthenticated)
    {
        <script>
    document.addEventListener("DOMContentLoaded", function() {
        var buttons = document.querySelectorAll('.add-to-cart');

        buttons.forEach(function(button) {
            button.addEventListener('click', function() {
                var productId = this.getAttribute('data-id');


                var xhr = new XMLHttpRequest();
                xhr.open('POST', '@Url.Action("AddToCart", "Cart")', true);
                xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');

                xhr.onreadystatechange = function() {
                    if (xhr.readyState === XMLHttpRequest.DONE) {
                        if (xhr.status === 200) {
                            var response = JSON.parse(xhr.responseText);
                            if (response.success) {
                                Toastify({
                                    text: "Item has been added to the cart",
                                    duration: 3000
                                }).showToast();
                            } else {
                                alert("There was an error adding the item to the cart.");
                            }
                        } else {
                            alert("There was an error with the request.");
                        }
                    }
                };
                xhr.send('bookId=' + encodeURIComponent(productId));
            });
        });
    });
        </script>
    }
    else
    {
        <script>
        document.addEventListener("DOMContentLoaded", function () {
            var buttons = document.querySelectorAll(".add-to-cart");

            buttons.forEach(function (button) {
                button.addEventListener("click", function () {
                    window.location.href = "@Url.Action("Login", "Account")"
                });
            });
        });
        </script>
    }
</div>